#!/bin/sh

quit()
{
	echo "Installation failed, try again."
	exit
}

### full install
./install-packages || quit

### install aur helper
which yay && echo "AUR helper already installed, skipping." || ./install-aur-helper || quit

### install some packages from the aur
./install-aur-packages || quit

### suckless
which st dwm dmenu dwmblocks && echo "Window manager already installed, skipping." || ./install-window-manager || quit

### user configuration
./user-config

### system configuration
./system-config
