#!/bin/sh

error()
{
	echo "Installation failed, try again."
	exit
}

### parallel downloads for pacman
./configure-pacman || error

### full install
./install-packages || error

### install aur helper
which yay && echo "AUR helper already installed, skipping." || ./install-aur-helper || error

### install some packages from the aur
./install-aur-packages || error

### suckless
which st dwm dmenu dwmblocks && echo "Window manager already installed, skipping." || ./install-window-manager || error

### user configuration
./user-config
