#!/bin/sh

error()
{
	echo "Installation failed, try again."
	exit
}

### parallel downloads for pacman
./configure-pacman || error

### basic install
sudo pacman -S --needed --noconfirm $(awk '/#M/{print $1}' resources/pkg-list) || error

### install aur helper
which yay && echo "AUR helper already installed, skipping." || ./install-aur-helper || error

### suckless
which st dwm dmenu dwmblocks && echo "Window manager already installed, skipping." || ./install-window-manager || error

### user configuration
./user-config
