#!/bin/sh

#pacman
pac_conf='/etc/pacman.conf'
sudo sed -i '/^#Color/s/^#//' $pac_conf
sudo sed -i 's/^#ParallelDownloads/ParallelDownloads = 5/' $pac_conf

# qemu/kvm

sudo systemctl enable libvirtd

libvirtd_conf='/etc/libvirt/libvirtd.conf'
sudo sed -i '/^#unix_sock_group = "libvirt"/s/^#//' $libvirtd_conf
sudo sed -i '/^#unix_sock_rw_perms = "0770"/s/^#//' $libvirtd_conf

sudo usermod -aG libvirt $USER
