#!/bin/sh

#pacman

sudo sed -i -E -e '/^#ParallelDownloads/ s/[0-9]+/5/g' \
	       -e '/^#Parallel/ s/^#//' \
	       -e '/^#Color/ s/^#//' /etc/pacman.conf

# qemu/kvm

sudo sed -i -e '/^#unix_sock_group = "libvirt"/s/^#//' \
	    -e '/^#unix_sock_rw_perms = "0770"/s/^#//' /etc/libvirt/libvirtd.conf

sudo systemctl enable libvirtd

sudo usermod -aG libvirt $USER
